### ISSUE TITLE
XInputNatives14

### ISSUE THREAD

**Issue by FusionLord** [StrikerX3/JXInput#7]
Unable to use any of the 14 library except isAvailable();

``` java
	public String getTitleInfo()
	{
		String s = "";

		System.out.println(XInputDevice14.isAvailable());

		for (XInputDevice14 device : devices)
		{
			if (device == null)
			{
				System.out.println("scrub controller is null");
				continue;
			}
				System.out.println(device.getCapabilities().getSupportedButtons());
				XInputBatteryInformation gamepadBattInfo = device.getBatteryInformation(XInputBatteryDeviceType.GAMEPAD);
				System.out.println("Gamepad battery: " + gamepadBattInfo.getType() + ", " + gamepadBattInfo.getLevel());
		}

		return s;
	}
```

>Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: com.ivan.xinput.natives.XInputNatives14.getCapabilities(IILjava/nio/ByteBuffer;)I
	at com.ivan.xinput.natives.XInputNatives14.getCapabilities(Native Method)
	at com.ivan.xinput.XInputDevice14.getCapabilities(XInputDevice14.java:113)
	at com.ivan.xinput.XInputDevice14.getCapabilities(XInputDevice14.java:99)
	at net.fusionlord.easyinterface.helper.ControllerUtil.getTitleInfo(ControllerUtil.java:50)
	at net.fusionlord.easyinterface.MainFrame.repaint(MainFrame.java:46)
	at java.awt.Component.repaint(Component.java:3346)
	at java.awt.Component.repaintParentIfNeeded(Component.java:2322)
	at java.awt.Component.reshape(Component.java:2310)
	at javax.swing.JComponent.reshape(JComponent.java:4216)
	at java.awt.Component.setBounds(Component.java:2253)
	at java.awt.BorderLayout.layoutContainer(BorderLayout.java:838)
	at java.awt.Container.layout(Container.java:1508)
	at java.awt.Container.doLayout(Container.java:1497)
	at java.awt.Container.validateTree(Container.java:1693)
	at java.awt.Container.validate(Container.java:1628)
	at java.awt.Window.dispatchEventImpl(Window.java:2748)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
>	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by FusionLord** [comment]
I rebuilt the Natives noticed that they larger when I rebuilt them, using your exact code, but that didn't fix the issue at hand.

**Comment by StrikerX3** [comment]
At one point I made some refactoring/renaming but did not update the natives. Since I did not have a Windows 8+ system to test that on, I was unable to check if it was working properly. Now that I have Windows 10 I found out what happened and fixed it.

**Comment by FusionLord** [comment]
Does that mean that you will be updating the repo?

**Comment by StrikerX3** [comment]
Yes, in a moment. Fixing a couple of conflicts right now.

**Comment by StrikerX3** [comment]
Only thing I didn't like was being forced to upgrade the C++ projects to VS 2015. Other than that, this commit should fix the issue. Just tested the 1.4 API and it seems to be working fine.

**Comment by FusionLord** [comment]
Thank you!
